{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "58b62299",
   "metadata": {},
   "source": [
    "# UNIDAD 6 — Notebook 2: Inventario de Herramientas del Curso\n",
    "## Mapea las Herramientas de U1–U5 a tu Proyecto\n",
    "\n",
    "**Duracion:** 1.5 horas  \n",
    "**Prerequisito:** Propuesta validada de U6_01 (`mi_proyecto_propuesta.json` guardado)\n",
    "\n",
    "---\n",
    "\n",
    "Este notebook carga tu propuesta, despliega el catalogo completo de herramientas del curso y te ayuda a construir el **Plan Tecnico** de tu proyecto: que modulos usaras, en que orden y como se conectan."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ec3e78d1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Propuesta cargada: [ESCRIBE EL TITULO DE TU PROYECTO AQUI]\n",
      "Herramientas seleccionadas: []\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "from pathlib import Path\n",
    "\n",
    "propuesta_file = Path(\"mi_proyecto_propuesta.json\")\n",
    "if propuesta_file.exists():\n",
    "    with open(propuesta_file, encoding=\"utf-8\") as f:\n",
    "        mi_propuesta = json.load(f)\n",
    "    herramientas_activas = [k for k, v in mi_propuesta[\"herramientas_a_usar\"].items() if v]\n",
    "    print(f\"Propuesta cargada: {mi_propuesta['titulo'].strip()[:60]}\")\n",
    "    print(f\"Herramientas seleccionadas: {herramientas_activas}\")\n",
    "else:\n",
    "    print(\"ADVERTENCIA: mi_proyecto_propuesta.json no encontrado.\")\n",
    "    print(\"Completa y ejecuta U6_01_PROPUESTA_PROYECTO.ipynb primero.\")\n",
    "    herramientas_activas = []"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "acc40f0a",
   "metadata": {},
   "source": [
    "---\n",
    "## Catalogo de Herramientas por Unidad\n",
    "\n",
    "Este catalogo lista todas las herramientas ensenadas en el curso, con descripcion, caso de uso tipico y snippet de codigo listo para copiar. Identifica cuales son relevantes para tu proyecto."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5762061a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Catalogo cargado: 14 unidades, 25 herramientas\n"
     ]
    }
   ],
   "source": [
    "CATALOGO = {\n",
    "\n",
    "    \"U1_modelado_atomistico\": [\n",
    "        {\n",
    "            \"nombre\": \"ASE — Atoms object\",\n",
    "            \"descripcion\": \"Representacion atomistica de moleculas y cristales\",\n",
    "            \"cuando_usar\": \"Cuando tu problema parte de estructuras moleculares/cristalinas\",\n",
    "            \"snippet\": \"\"\"from ase import Atoms\\nnano = Atoms('Au13', positions=...)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Descriptores de Coulomb / fingerprints\",\n",
    "            \"descripcion\": \"Convierte estructuras atomisticas en vectores numericos para ML\",\n",
    "            \"cuando_usar\": \"Como entrada a modelos de ML cuando tienes estructuras\",\n",
    "            \"snippet\": \"\"\"from dscribe.descriptors import CoulombMatrix\\ncm = CoulombMatrix(n_atoms_max=20)\\nX = cm.create(atoms_list)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"EMT / VASP / Quantum ESPRESSO\",\n",
    "            \"descripcion\": \"Calculadoras de energia para estructuras atomisticas\",\n",
    "            \"cuando_usar\": \"Para relajar estructuras o calcular energias de formacion\",\n",
    "            \"snippet\": \"\"\"from ase.calculators.emt import EMT\\natoms.calc = EMT()\\nenergy = atoms.get_potential_energy()\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U2_simulacion_MD_DFT\": [\n",
    "        {\n",
    "            \"nombre\": \"Dinamica Molecular (ASE NVT/NVE)\",\n",
    "            \"descripcion\": \"Simula la evolucion temporal de sistemas atomisticos\",\n",
    "            \"cuando_usar\": \"Para estudiar estabilidad termica, difusion, propiedades dinamicas\",\n",
    "            \"snippet\": \"\"\"from ase.md.langevin import Langevin\\ndyn = Langevin(atoms, timestep=5*units.fs, temperature_K=300, friction=0.01)\\ndyn.run(steps=1000)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Optimizacion geometrica (BFGS)\",\n",
    "            \"descripcion\": \"Minimiza la energia de una estructura hasta el minimo local\",\n",
    "            \"cuando_usar\": \"Para obtener la estructura de menor energia (geometria de equilibrio)\",\n",
    "            \"snippet\": \"\"\"from ase.optimize import BFGS\\nopt = BFGS(atoms)\\nopt.run(fmax=0.05)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"NEB — Nudged Elastic Band\",\n",
    "            \"descripcion\": \"Calcula barreras de energia entre dos estados\",\n",
    "            \"cuando_usar\": \"Para calcular energias de activacion de reacciones\",\n",
    "            \"snippet\": \"\"\"from ase.neb import NEB\\nneb = NEB(images)\\nneb.interpolate()\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U3_ml_clasico\": [\n",
    "        {\n",
    "            \"nombre\": \"Random Forest / XGBoost\",\n",
    "            \"descripcion\": \"Modelos de ensemble para regresion y clasificacion\",\n",
    "            \"cuando_usar\": \"Para predicciones sobre datasets tabulares de propiedades de materiales\",\n",
    "            \"snippet\": \"\"\"from sklearn.ensemble import RandomForestRegressor\\nmodel = RandomForestRegressor(n_estimators=200, random_state=42)\\nmodel.fit(X_train, y_train)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Gaussian Process Regression\",\n",
    "            \"descripcion\": \"Modelo probabilistico con estimacion de incertidumbre\",\n",
    "            \"cuando_usar\": \"Cuando necesitas saber no solo la prediccion sino su incertidumbre\",\n",
    "            \"snippet\": \"\"\"from sklearn.gaussian_process import GaussianProcessRegressor\\ngpr = GaussianProcessRegressor()\\ny_pred, y_std = gpr.predict(X_test, return_std=True)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Optimizacion Bayesiana (scikit-optimize)\",\n",
    "            \"descripcion\": \"Optimiza funciones costosas con pocos evaluaciones\",\n",
    "            \"cuando_usar\": \"Para optimizar hiperparametros o parametros de sintesis\",\n",
    "            \"snippet\": \"\"\"from skopt import gp_minimize\\nresult = gp_minimize(objective, dimensions, n_calls=50, random_state=42)\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U3_redes_neuronales\": [\n",
    "        {\n",
    "            \"nombre\": \"MLP (PyTorch)\",\n",
    "            \"descripcion\": \"Red neuronal densa para regresion/clasificacion\",\n",
    "            \"cuando_usar\": \"Cuando el dataset es grande y el espacio de entrada es denso\",\n",
    "            \"snippet\": \"\"\"import torch.nn as nn\\nmodel = nn.Sequential(nn.Linear(n_in, 128), nn.ReLU(), nn.Linear(128, n_out))\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Transfer Learning (torchvision)\",\n",
    "            \"descripcion\": \"Reutiliza modelos pre-entrenados en imagenes\",\n",
    "            \"cuando_usar\": \"Para datos de microscopia electronica (SEM, TEM) o espectros\",\n",
    "            \"snippet\": \"\"\"from torchvision.models import resnet18\\nmodel = resnet18(pretrained=True)\\nmodel.fc = nn.Linear(512, n_classes)\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U4_llms_generativa\": [\n",
    "        {\n",
    "            \"nombre\": \"Embeddings de texto (sentence-transformers)\",\n",
    "            \"descripcion\": \"Convierte texto cientifico en vectores semanticos\",\n",
    "            \"cuando_usar\": \"Para buscar literatura, clasificar papers, extraer informacion\",\n",
    "            \"snippet\": \"\"\"from sentence_transformers import SentenceTransformer\\nmodel = SentenceTransformer('all-MiniLM-L6-v2')\\nvecs = model.encode(corpus)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"LLM para analisis de espectros / datos\",\n",
    "            \"descripcion\": \"Usa LLMs para interpretar datos experimentales\",\n",
    "            \"cuando_usar\": \"Para generar interpretaciones automaticas de resultados\",\n",
    "            \"snippet\": \"\"\"from langchain_openai import ChatOpenAI\\nllm = get_llm()  # Routing: OpenRouter -> Gemini 2.5 -> OpenAI -> Ollama (ver .env.example)\\nrespuesta = llm.invoke(f'Interpreta este espectro: {datos}')\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U5_agentes_langchain\": [\n",
    "        {\n",
    "            \"nombre\": \"Agente ReAct (LangChain)\",\n",
    "            \"descripcion\": \"Agente que razona y usa herramientas iterativamente\",\n",
    "            \"cuando_usar\": \"Para tareas que requieren multiples pasos de razonamiento\",\n",
    "            \"snippet\": \"\"\"from langgraph.prebuilt import create_react_agent  # LangGraph 0.2+\\nagente = create_react_agent(llm, tools, prompt)\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Context Loader (U5 skill)\",\n",
    "            \"descripcion\": \"Precalienta agentes con contexto del dominio\",\n",
    "            \"cuando_usar\": \"Al inicio de cada sesion de trabajo del agente\",\n",
    "            \"snippet\": \"\"\"from external_skills.agent_warmup import context_loader\\nctx = context_loader.load_context(dominio='nanotecnologia')\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U5_multiagente_crewai\": [\n",
    "        {\n",
    "            \"nombre\": \"CrewAI — multiples agentes cooperativos\",\n",
    "            \"descripcion\": \"Orquesta equipos de agentes con roles especializados\",\n",
    "            \"cuando_usar\": \"Para proyectos con fases claramente separadas (datos, modelo, reporte)\",\n",
    "            \"snippet\": \"\"\"from crewai import Crew, Agent, Task\\ncrew = Crew(agents=[agente_datos, agente_modelo], tasks=[tarea_eda, tarea_modelado])\\nresult = crew.kickoff()\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U5_rag_memoria\": [\n",
    "        {\n",
    "            \"nombre\": \"RAG — Retrieval Augmented Generation\",\n",
    "            \"descripcion\": \"Conecta LLMs con bases de conocimiento vectoriales\",\n",
    "            \"cuando_usar\": \"Para que el LLM responda con informacion de papers propios\",\n",
    "            \"snippet\": \"\"\"# LCEL (LangChain 0.3+):\n",
    "# chain = retriever | prompt | llm | StrOutputParser()\\nqa_chain = RetrievalQA.from_chain_type(llm=llm, retriever=vectorstore.as_retriever())\\n\"\"\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Graph Memory (U5 skill)\",\n",
    "            \"descripcion\": \"Almacena relaciones entre entidades en memoria de grafo\",\n",
    "            \"cuando_usar\": \"Para rastrear relaciones entre experimentos, hipotesis y resultados\",\n",
    "            \"snippet\": \"\"\"from external_skills.memory.graph_memory import GraphMemory\\ngm = GraphMemory()\\ngm.add_edge('experimento_1', 'resultado_1', 'produjo')\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "    \"U6_api_fastapi\": [\n",
    "        {\n",
    "            \"nombre\": \"FastAPI — servicio REST\",\n",
    "            \"descripcion\": \"Expone tu modelo como API web con documentacion automatica\",\n",
    "            \"cuando_usar\": \"Para compartir tu modelo o integrarlo en otras aplicaciones\",\n",
    "            \"snippet\": \"\"\"from fastapi import FastAPI\\napp = FastAPI()\\n@app.post('/predict')\\ndef predict(data: InputSchema): return {'result': model.predict(data.features)}\\n\"\"\"\n",
    "        },\n",
    "    ],\n",
    "    \"U5_smolagents\": [\n",
    "        {\n",
    "            \"nombre\": \"smolagents CodeAgent (HuggingFace)\",\n",
    "            \"descripcion\": \"Agente que escribe y ejecuta Python como accion. Ver U5_01 Seccion 8.5.\",\n",
    "            \"cuando_usar\": \"Analisis exploratorio ad-hoc, tasks sin schema fijo, composicion libre de tools\",\n",
    "            \"snippet\": \"from smolagents import CodeAgent, LiteLLMModel\\nmodel = LiteLLMModel('openrouter/google/gemini-2.5-flash', api_key=os.getenv('OPENROUTER_API_KEY'))\\nagent = CodeAgent(tools=[], model=model)\\nresult = agent.run('Analiza propiedades de Au nanoclusters 2024')\\n\"\n",
    "        },\n",
    "    ],\n",
    "    \"U5_google_adk\": [\n",
    "        {\n",
    "            \"nombre\": \"Google ADK Agent + A2A Protocol\",\n",
    "            \"descripcion\": \"Framework enterprise para agentes con protocolo Agent-to-Agent. Ver U5_04.\",\n",
    "            \"cuando_usar\": \"Integracion con Google Cloud, Vertex AI, sistemas multi-agente corporativos\",\n",
    "            \"snippet\": \"from google.adk.agents import Agent\\nfrom google.adk.tools import FunctionTool\\n\\n@FunctionTool\\ndef analizar_espectro(datos: str) -> str:\\n    return 'resultado_analisis'\\n\\nagente = Agent(name='nano_agent', model='gemini-2.0-flash', tools=[analizar_espectro])\\n\"\n",
    "        },\n",
    "    ],\n",
    "    \"U5_mcp\": [\n",
    "        {\n",
    "            \"nombre\": \"MCP (Model Context Protocol)\",\n",
    "            \"descripcion\": \"Estandar abierto para exponer tools de investigacion a cualquier cliente LLM. Ver U5_04 Sec 6.4.\",\n",
    "            \"cuando_usar\": \"Cuando quieres que Claude Desktop, VS Code u otros clientes consuman tus herramientas\",\n",
    "            \"snippet\": \"from mcp.server import Server\\nfrom mcp import types\\n\\napp = Server('nano-research-mcp')\\n\\n@app.list_tools()\\nasync def list_tools():\\n    return [types.Tool(name='calcular_energia',\\n                       description='EMT energy',\\n                       inputSchema={'type': 'object', 'properties': {'formula': {'type': 'string'}}})]\\n\"\n",
    "        },\n",
    "    ],\n",
    "    \"U5_graph_rag\": [\n",
    "        {\n",
    "            \"nombre\": \"Graph RAG — NetworkX (prototipo en memoria)\",\n",
    "            \"descripcion\": \"Knowledge graph de relaciones entre materiales, autores y experimentos. Ver U5_06.\",\n",
    "            \"cuando_usar\": \"Prototipo rapido, grafos < 100K nodos, sin persistencia entre sesiones\",\n",
    "            \"snippet\": \"import networkx as nx\\nG = nx.DiGraph()\\nG.add_node('Au13', tipo='nanoparticula', tamano_nm=1.8)\\nG.add_node('ZnO', tipo='semiconductor', band_gap_eV=3.37)\\nG.add_edge('Au13', 'ZnO', relacion='cataliza', temp_K=300)\\nprint(list(G.neighbors('Au13')))\\n\"\n",
    "        },\n",
    "        {\n",
    "            \"nombre\": \"Graph RAG — Kuzu (persistente, sin servidor)\",\n",
    "            \"descripcion\": \"Grafo embebido con Cypher. Persiste en disco, compatible con Neo4j queries. Ver U5_06.\",\n",
    "            \"cuando_usar\": \"Investigacion local, grafos medianos, cuando quieres Cypher sin levantar servidor\",\n",
    "            \"snippet\": \"import kuzu\\ndb = kuzu.Database('mi_grafo_nano')\\nconn = kuzu.Connection(db)\\nconn.execute('CREATE NODE TABLE Material(nombre STRING, PRIMARY KEY(nombre))')\\nconn.execute(\\\"MERGE (:Material {nombre: 'Au13'})\\\")\\nresultados = conn.execute('MATCH (m:Material) RETURN m.nombre').fetchall()\\n\"\n",
    "        },\n",
    "    ],\n",
    "    \"U5_langsmith\": [\n",
    "        {\n",
    "            \"nombre\": \"LangSmith — Observabilidad de agentes\",\n",
    "            \"descripcion\": \"Traza y evalua cada ejecucion de cadenas y agentes LangChain/LangGraph.\",\n",
    "            \"cuando_usar\": \"Siempre en produccion; indispensable cuando un agente falla de forma no reproducible\",\n",
    "            \"snippet\": \"import os\\nos.environ['LANGSMITH_TRACING'] = 'true'\\nos.environ['LANGSMITH_API_KEY'] = os.getenv('LANGSMITH_API_KEY', '')\\nos.environ['LANGSMITH_PROJECT'] = 'nano-research-u6'\\n# Todas las invocaciones LangChain se trazan automaticamente en smith.langchain.com\\n\"\n",
    "        },\n",
    "    ],\n",
    "\n",
    "}\n",
    "\n",
    "total = sum(len(v) for v in CATALOGO.values())\n",
    "print(f\"Catalogo cargado: {len(CATALOGO)} unidades, {total} herramientas\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3e619673",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No hay herramientas seleccionadas. Carga tu propuesta primero.\n",
      "Mostrando todas las herramientas disponibles en el catalogo:\n",
      "\n",
      "[U1_MODELADO_ATOMISTICO]\n",
      "  * ASE — Atoms object\n",
      "  * Descriptores de Coulomb / fingerprints\n",
      "  * EMT / VASP / Quantum ESPRESSO\n",
      "\n",
      "[U2_SIMULACION_MD_DFT]\n",
      "  * Dinamica Molecular (ASE NVT/NVE)\n",
      "  * Optimizacion geometrica (BFGS)\n",
      "  * NEB — Nudged Elastic Band\n",
      "\n",
      "[U3_ML_CLASICO]\n",
      "  * Random Forest / XGBoost\n",
      "  * Gaussian Process Regression\n",
      "  * Optimizacion Bayesiana (scikit-optimize)\n",
      "\n",
      "[U3_REDES_NEURONALES]\n",
      "  * MLP (PyTorch)\n",
      "  * Transfer Learning (torchvision)\n",
      "\n",
      "[U4_LLMS_GENERATIVA]\n",
      "  * Embeddings de texto (sentence-transformers)\n",
      "  * LLM para analisis de espectros / datos\n",
      "\n",
      "[U5_AGENTES_LANGCHAIN]\n",
      "  * Agente ReAct (LangChain)\n",
      "  * Context Loader (U5 skill)\n",
      "\n",
      "[U5_MULTIAGENTE_CREWAI]\n",
      "  * CrewAI — multiples agentes cooperativos\n",
      "\n",
      "[U5_RAG_MEMORIA]\n",
      "  * RAG — Retrieval Augmented Generation\n",
      "  * Graph Memory (U5 skill)\n",
      "\n",
      "[U6_API_FASTAPI]\n",
      "  * FastAPI — servicio REST\n",
      "\n",
      "[U5_SMOLAGENTS]\n",
      "  * smolagents CodeAgent (HuggingFace)\n",
      "\n",
      "[U5_GOOGLE_ADK]\n",
      "  * Google ADK Agent + A2A Protocol\n",
      "\n",
      "[U5_MCP]\n",
      "  * MCP (Model Context Protocol)\n",
      "\n",
      "[U5_GRAPH_RAG]\n",
      "  * Graph RAG — NetworkX (prototipo en memoria)\n",
      "  * Graph RAG — Kuzu (persistente, sin servidor)\n",
      "\n",
      "[U5_LANGSMITH]\n",
      "  * LangSmith — Observabilidad de agentes\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "#   HERRAMIENTAS RELEVANTES PARA TU PROYECTO\n",
    "#   Muestra solo las herramientas de las unidades que elegiste\n",
    "# ============================================================\n",
    "\n",
    "# Fallback robusto en caso de ejecucion fuera de orden\n",
    "if 'herramientas_activas' not in globals():\n",
    "    herramientas_activas = []\n",
    "\n",
    "if 'CATALOGO' not in globals():\n",
    "    CATALOGO = {}\n",
    "\n",
    "if herramientas_activas:\n",
    "    print(\"HERRAMIENTAS DISPONIBLES PARA TU PROYECTO\")\n",
    "    print(\"=\" * 60)\n",
    "    for clave in herramientas_activas:\n",
    "        categoria = CATALOGO.get(clave, [])\n",
    "        if categoria:\n",
    "            print(f\"\\n[{clave.upper()}]\")\n",
    "            for h in categoria:\n",
    "                print(f\"  * {h['nombre']}\")\n",
    "                print(f\"    Cuando usar: {h['cuando_usar']}\")\n",
    "else:\n",
    "    print(\"No hay herramientas seleccionadas. Carga tu propuesta primero.\")\n",
    "    print(\"Mostrando todas las herramientas disponibles en el catalogo:\")\n",
    "    for clave, herramientas in CATALOGO.items():\n",
    "        print(f\"\\n[{clave.upper()}]\")\n",
    "        for h in herramientas:\n",
    "            print(f\"  * {h['nombre']}\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7ecf98da",
   "metadata": {},
   "source": [
    "---\n",
    "## Tu Plan Tecnico\n",
    "\n",
    "Describe el pipeline de tu proyecto: como fluyen los datos desde la entrada hasta el resultado final. Usa el siguiente diagrama como plantilla."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "634334a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PIPELINE TECNICO DE TU PROYECTO\n",
      "-------------------------------------------------------\n",
      "  Paso 1: Etapa 1\n",
      "    Hace     : ...\n",
      "    Herramienta: ...\n",
      "  Paso 2: Etapa 2\n",
      "    Hace     : ...\n",
      "    Herramienta: ...\n",
      "  Paso 3: Etapa 3\n",
      "    Hace     : ...\n",
      "    Herramienta: ...\n",
      "\n",
      "Completa todos los campos '...' del pipeline antes de continuar.\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "#   DEFINE TU PIPELINE TECNICO\n",
    "#   Describe cada etapa de tu proyecto y la herramienta que usas\n",
    "# ============================================================\n",
    "\n",
    "mi_pipeline = [\n",
    "    # Formato: (etapa, descripcion_lo_que_hace, herramienta_del_catalogo)\n",
    "    (\"Adquisición de datos\", \"Descarga de datos estructurales y band gaps de óxidos metálicos usando Materials Project API\", \"U1_modelado_atomistico\"),\n",
    "    (\"Extracción de descriptores\", \"Generación de características químicas y geométricas (electronegatividad, volumen, coordinación) con pymatgen y ASE\", \"U1_modelado_atomistico\"),\n",
    "    (\"Entrenamiento de modelos de ML\", \"Ajuste de modelos clásicos de ensamble (Random Forest, Gradient Boosting) y redes neuronales MLP para predecir el bandgap\", \"U3_ml_clasico\"),\n",
    "    (\"RAG de literatura de soporte\", \"Búsqueda semántica en base de datos de papers vectorizada para validar experimentalmente los bandgaps predichos\", \"U5_rag_memoria\"),\n",
    "    (\"Despliegue de API REST\", \"Creación de un endpoint FastAPI para exponer el modelo y permitir screening de nuevos óxidos metálicos\", \"U6_api_fastapi\")\n",
    "]\n",
    "\n",
    "# Validar que no quedaron placeholders\n",
    "pipeline_valido = all(\n",
    "    etapa[1] not in (\"...\", \"\") and etapa[2] not in (\"...\", \"\")\n",
    "    for etapa in mi_pipeline\n",
    ")\n",
    "\n",
    "print(\"PIPELINE TECNICO DE TU PROYECTO\")\n",
    "print(\"-\" * 55)\n",
    "for i, (nombre, descripcion, herramienta) in enumerate(mi_pipeline, 1):\n",
    "    print(f\"  Paso {i}: {nombre}\")\n",
    "    print(f\"    Hace     : {descripcion}\")\n",
    "    print(f\"    Herramienta: {herramienta}\")\n",
    "\n",
    "print()\n",
    "if pipeline_valido:\n",
    "    print(\"Pipeline listo. Continua con U6_03_IMPLEMENTACION_PROYECTO.ipynb\")\n",
    "else:\n",
    "    print(\"Completa todos los campos '...' del pipeline antes de continuar.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "0b630f60",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Plan tecnico guardado en mi_proyecto_plan_tecnico.json\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "from pathlib import Path\n",
    "\n",
    "plan = {\n",
    "    \"propuesta_titulo\": mi_propuesta.get(\"titulo\", \"\") if 'mi_propuesta' in dir() else \"\",\n",
    "    \"herramientas_seleccionadas\": herramientas_activas,\n",
    "    \"pipeline\": [{\"etapa\": e[0], \"descripcion\": e[1], \"herramienta\": e[2]} for e in mi_pipeline],\n",
    "    \"pipeline_completo\": pipeline_valido,\n",
    "}\n",
    "\n",
    "with open(\"mi_proyecto_plan_tecnico.json\", \"w\", encoding=\"utf-8\") as f:\n",
    "    json.dump(plan, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "print(\"Plan tecnico guardado en mi_proyecto_plan_tecnico.json\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e48989ac",
   "metadata": {},
   "source": [
    "---\n",
    "## Siguiente\n",
    "\n",
    "[U6_03_IMPLEMENTACION_PROYECTO.ipynb](U6_03_IMPLEMENTACION_PROYECTO.ipynb) — Scaffold de implementacion que adaptas a tu problema."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ia_nano",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}