import json

path = r'c:\Users\yesiz\OneDrive\Documentos\Modelado IA\Antigravity-Nano-Research-Multiagentic-Core-main\Tarea 1.ipynb'

with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## Tarea 3: Investigacion - Baletto and Ferrando (2005)\n",
            "\n",
            "> **Referencia:** Baletto, F. and Ferrando, R. *Structural properties of nanoclusters: Energetic, thermodynamic, and kinetic effects.* **Reviews of Modern Physics** 77, 371-423 (2005). DOI: 10.1103/RevModPhys.77.371\n",
            "\n",
            "---\n",
            "Esta revision es la mas completa y citada sobre propiedades estructurales de nanoclusters metalicos. "
            "Combina simulacion atomistica (Dinamica Molecular, Monte Carlo, optimizacion global) con resultados "
            "experimentales (microscopia TEM, espectroscopia de masas). Se responden las tres preguntas planteadas "
            "de forma detallada y precisa."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Pregunta 1 — Que estructuras son mas estables para clusters metalicos de menos de 100 atomos?\n",
            "\n",
            "#### Contexto: el paisaje de energia potencial a nanoescala\n",
            "\n",
            "Para clusters de menos de 100 atomos, la estructura de minima energia **no** replica el cristal bulk (FCC/BCC).\n",
            "Segun Baletto and Ferrando (2005), compiten tres familias estructurales:\n",
            "\n",
            "| Motivo | Descripcion | Ventaja | Desventaja |\n",
            "|--------|-------------|---------|------------|\n",
            "| **Icosaedro de Mackay** | Estructura no cristalina, simetria 5-fold, 20 caras (111) distorsionadas, capas concentricas. | Minimiza energia superficial (solo facetas (111)). Optimo para N pequeno. | Genera distorsion elastica interna (compresion) creciente con N. Incompatible con FCC. |\n",
            "| **Decaedro (Ino/Marks)** | Estructura no cristalina, prismas pentagonales unidos por maclas. Facetas (111) y (100). | Menor strain que el icosaedro; balance superficie-volumen optimo para tamanos intermedios. | Menor esfericidad; requiere truncaciones de Marks para estabilizarse. |\n",
            "| **Octaedro truncado (FCC)** | Estructura cristalina, fragmento del bulk. Facetas (111) y (100). | Compatible con bulk; mas estable para N grande (~N > 1000). | Peor relacion superficie/volumen a N pequeno. |\n",
            "\n",
            "#### Conclusion del articulo\n",
            "\n",
            "Para **N = 13-100 atomos**, el **icosaedro de Mackay** es la estructura predominantemente mas estable para\n",
            "la mayoria de metales nobles y de transicion (Au, Ag, Cu, Pd, Pt, Ni). Razones:\n",
            "\n",
            "1. **Maximizacion del empaquetamiento superficial**: Expone solo caras (111), las mas compactas.\n",
            "2. **Dominio de la superficie**: Para N pequeno la energia de superficie domina al volumen; el strain aun tolerable.\n",
            "3. **Simetria esferica optima**: Menor cociente superficie/volumen entre todas las geometrias no cristalinas.\n",
            "\n",
            "**Jerarquia energetica general (N = 13-100):**\n",
            "\n",
            "    Icosaedro (mas estable)  >>  Decaedro  >>  Octaedro truncado FCC\n",
            "\n",
            "**Excepcion notable — Au**: Los efectos relativistas favorecen estructuras planas (*planar*) para N < 10-12\n",
            "atomos, antes de que emerjan los icosaedros. Esto hace del Au un caso unico entre los metales nobles.\n",
            "\n",
            "Los magic numbers del icosaedro dentro del rango < 100 son: **N = 13 y N = 55**."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Pregunta 2 — Como afecta el magic number a la estabilidad?\n",
            "\n",
            "#### Definicion\n",
            "\n",
            "Un **numero magico** es un valor de N para el cual un cluster presenta estabilidad\n",
            "**significativamente mayor** que sus vecinos N-1 y N+1. Se manifiesta como:\n",
            "- Picos de abundancia en espectros de masas (experimento)\n",
            "- Minimos locales profundos en la energia de exceso (teoria)\n",
            "\n",
            "#### Origen: capas concentricas cerradas\n",
            "\n",
            "Los magic numbers del icosaedro de Mackay provienen del cierre de capas concentricas.\n",
            "Formula general para k capas completas:\n",
            "\n",
            "    N_k = (10k^3 - 15k^2 + 11k - 3) / 3\n",
            "\n",
            "| Capa k | Atomos en la capa | N total (magic) | En rango < 100 |\n",
            "|--------|-------------------|-----------------|----------------|\n",
            "| 1 | 1   | 1   | (atomo unico) |\n",
            "| 2 | 12  | 13  | SI |\n",
            "| 3 | 42  | 55  | SI |\n",
            "| 4 | 92  | 147 | NO (limite) |\n",
            "| 5 | 162 | 309 | NO |\n",
            "\n",
            "#### Cuantificacion: segunda diferencia de energia\n",
            "\n",
            "Baletto and Ferrando usan la segunda diferencia de energia para medir la estabilidad relativa:\n",
            "\n",
            "    Delta2_E(N) = E(N+1) + E(N-1) - 2*E(N)\n",
            "\n",
            "Un pico positivo en Delta2_E(N) indica que el cluster N es mas estable que sus vecinos (magic number).\n",
            "\n",
            "#### Consecuencias practicas\n",
            "\n",
            "1. **Barreras de crecimiento**: Los magic numbers son puntos de estancamiento; anadir el siguiente\n",
            "   atomo requiere iniciar una nueva capa (mayor costo energetico).\n",
            "2. **Mayor T de fusion relativa**: Los clusters en magic numbers presentan temperaturas de fusion\n",
            "   ligeramente superiores a sus vecinos, reflejo de su mayor cohesion.\n",
            "3. **Abundancia experimental**: En espectroscopia de masas de Ag y Cu gaseosos, N = 13 y N = 55\n",
            "   aparecen con mayor abundancia que sus vecinos, confirmando la teoria.\n",
            "4. **Atenuacion a mayor N**: Para N > 300, la diferencia energetica entre magic y no-magic se vuelve\n",
            "   comparable a la energia termica a temperatura ambiente. El efecto pierde determinismo.\n",
            "5. **Magic numbers decaedricos (Marks)**: El articulo reporta magic numbers tambien para decaedros\n",
            "   de Marks, que compiten con los icosaedros en el rango N = 75-200. Para Ag y Cu existen\n",
            "   configuraciones decaedricas mas estables que icosaedros incompletos de igual tamano."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Pregunta 3 — Que es la transicion icosaedrica-decaedrica?\n",
            "\n",
            "#### Definicion\n",
            "\n",
            "La **transicion icosaedrica-decaedrica** (tambien llamada *Ino-Marks crossover*) es el cambio del\n",
            "motivo estructural de minima energia global de un cluster metalico, pasando de geometria\n",
            "**icosaedrica** a **decaedrica** al incrementar N hasta un valor critico N*.\n",
            "\n",
            "#### Mecanismo fisico: competencia de dos energias\n",
            "\n",
            "| Fuerza | Efecto | Beneficiado |\n",
            "|--------|--------|-------------|\n",
            "| **Energia de superficie** | El icosaedro expone solo facetas (111); mejor relacion sup/vol para N pequeno | Icosaedro |\n",
            "| **Strain elastico interno** | El icosaedro comprime atomos internos; distorsion crece ~N (proporcional al volumen) | Decaedro (menor strain) |\n",
            "\n",
            "Existe N* donde la penalizacion elastica del icosaedro supera su ventaja superficial y el\n",
            "decaedro se vuelve mas estable.\n",
            "\n",
            "#### Modelo analitico de Baletto et al.\n",
            "\n",
            "La energia de exceso de cada motivo escala como:\n",
            "\n",
            "    E_exceso(Ico)  ~ a_surf * N^(2/3) + a_strain * N\n",
            "    E_exceso(Deca) ~ b_surf * N^(2/3) + b_strain * N\n",
            "\n",
            "El cruce ocurre cuando ambas se igualan:\n",
            "\n",
            "    N* ~ (a_surf - b_surf) / (b_strain - a_strain)\n",
            "\n",
            "El parametro clave es B/E_coh (modulo volumetrico / energia de cohesion), que mide la\n",
            "resistencia elastica del metal: mayor B/E_coh → mayor penalizacion por strain → N* menor\n",
            "(el icosaedro se vuelve inestable antes).\n",
            "\n",
            "#### Tamanos de cruce N* reportados por metal\n",
            "\n",
            "| Metal | N* Ico → Deca | N* Deca → FCC | Intervalo Ico |\n",
            "|-------|---------------|---------------|---------------|\n",
            "| **Cu** | ~100 atomos | ~3 000 atomos | Amplio |\n",
            "| **Ag** | ~100-200 atomos | ~5 000 atomos | Amplio |\n",
            "| **Au** | < 30 atomos (o ausente) | ~300-500 atomos | Muy estrecho o nulo |\n",
            "| **Pd** | ~100 atomos | ~1 000-2 000 atomos | Moderado |\n",
            "| **Ni / Pt** | ~150-300 atomos | > 10 000 atomos | Muy amplio |\n",
            "\n",
            "#### Efecto de la temperatura\n",
            "\n",
            "Baletto and Ferrando destacan que la transicion tambien ocurre **como funcion de T**:\n",
            "\n",
            "- A T baja: domina la energia potencial → icosaedros para N < N*.\n",
            "- Al aumentar T: la entropia configuracional (mayor en decaedros por menor simetria) favorece\n",
            "  decaedros. El cruce se desplaza hacia N menores.\n",
            "- **Implicacion cinetica**: Clusters formados a T alta (ablacion laser, llama) pueden quedar\n",
            "  atrapados en geometrias decaedricas que no son el minimo de energia a T ambiente.\n",
            "\n",
            "#### Relevancia aplicada\n",
            "\n",
            "1. **Catalisis**: Ico expone solo (111); Marks-Deca expone (111) y (100). La reactividad catalitica\n",
            "   depende directamente de que cara es dominante. El cruce Ico→Deca cambia el sitio activo.\n",
            "2. **Plasmonica (Au, Ag)**: El espectro SPR depende de la forma. Particulas pentagonales (Deca)\n",
            "   vs esfericas (Ico) presentan longitudes de onda plasmonicas significativamente diferentes.\n",
            "3. **Sintesis controlada**: Ajustando T, presion o ligandos durante la sintesis, es posible\n",
            "   seleccionar el motivo geometrico y optimizar propiedades especificas de la nanoparticula.\n",
            "\n",
            "---\n",
            "### Resumen ejecutivo — Tarea 3\n",
            "\n",
            "| Pregunta | Respuesta clave (Baletto and Ferrando, 2005) |\n",
            "|----------|----------------------------------------------|\n",
            "| Estructura mas estable < 100 atomos | **Icosaedro de Mackay** (magic: N=13 y N=55) para la mayoria de metales nobles. Excepcion: Au, que puede adoptar geometrias planas para N < 12. |\n",
            "| Efecto del magic number | Picos de estabilidad en Delta2_E, mayor T de fusion relativa, picos experimentales en espectros de masa. El efecto se atenua para N > 300. Existen tambien magic numbers decaedricos (Marks). |\n",
            "| Transicion Ico → Deca | Crossover energetico cuando el strain elastico del icosaedro supera su ventaja superficial. N* depende del metal: Cu ~100, Ag ~100-200, Au < 30 atomos. Temperatura desplaza el cruce. Relevante para catalisis y plasmonica. |\n",
            "\n",
            "---\n",
            "### Referencia\n",
            "\n",
            "Baletto, F. and Ferrando, R. (2005). Structural properties of nanoclusters: Energetic, thermodynamic, "
            "and kinetic effects. *Reviews of Modern Physics*, 77(1), 371-423. "
            "https://doi.org/10.1103/RevModPhys.77.371"
        ]
    }
]

nb['cells'].extend(new_cells)

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=4)

print(f"OK: {len(new_cells)} celdas de Tarea 3 agregadas. Total celdas: {len(nb['cells'])}")
